all:
	echo "ChunkConsecutive.run" | iex -S mix
	echo "ChunkOverlapping.run" | iex -S mix
	echo "ChunkUsingEnum.run_sum_consecutive" | iex -S mix
	echo "ChunkUsingEnum.run_sum_overlapping" | iex -S mix

clean:
	rm -rf _build
