all:
	ghc -o impossible_dates impossible_dates.hs
	ghc -o maybe_impossible_dates maybe_impossible_dates.hs
	ghc -o impossible_times impossible_times.hs

clean:
	rm -f impossible_dates.hi impossible_dates.o impossible_dates
	rm -f maybe_impossible_dates.hi maybe_impossible_dates.o maybe_impossible_dates
	rm -f impossible_times.hi impossible_times.o impossible_times
