all:
	ghc -o foldl-subtract-one-zero foldl-subtract-one-zero.hs
	./foldl-subtract-one-zero

	ghc -o foldl-add-1-to-3 foldl-add-1-to-3.hs
	./foldl-add-1-to-3

	ghc -o foldl-add-1-to-3-string foldl-add-1-to-3-string.hs
	./foldl-add-1-to-3-string

	ghc -o foldr-add-1-to-3-string foldr-add-1-to-3-string.hs
	./foldr-add-1-to-3-string

	ghc -o incl incl.hs
	./incl

	ghc -o incr incr.hs
	./incr

clean:
	rm -f *.hi
	rm -f *.o
	rm -f foldl-subtract-one-zero
	rm -f foldl-add-1-to-3
	rm -f foldl-add-1-to-3-string
	rm -f foldr-add-1-to-3-string
	rm -f incl
	rm -f incr
