all:
	yarn install
	cat reduce-sum.js | node
	cat reduce-add-1-to-3.js | node
	cat add-1-to-3.js | node
	cat reduce-add-1-to-3-string.js | node
	cat reduce-right-add-1-to-3-string.js | node
	cat reduce-reverse-add-1-to-3-string.js | node

clean:
	rm -rf node_modules
	rm -f yarn.lock
	rm -f yarn-error.log
